version: "3.8"

services:

  # ─── FRONTEND React ───────────────────────────────
  frontend:
    build: ./frontend
    container_name: polychat_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend
    networks:
      - mongo_net

  # ─── BACKEND Flask ────────────────────────────────
  backend:
    build: ./backend
    container_name: polychat_backend
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - mongo-init
      - redis
    networks:
      - mongo_net

  # ─── REDIS ────────────────────────────────────────
  redis:
    image: redis:7
    container_name: polychat_redis
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - mongo_net

  # ─── REPLICASET MongoDB ───────────────────────────
  mongo1:
    image: mongo:7
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27027:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo_net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo_net

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo_net

  # ─── INIT ReplicaSet + Collections (exécuté une seule fois) ───
  mongo-init:
    image: mongo:7
    container_name: mongo-init
    depends_on:
      mongo1:
        condition: service_healthy
    networks:
      - mongo_net
    restart: "no"
    volumes:
      - ./database/init-mongo.sh:/usr/local/bin/init-mongo.sh:ro
    entrypoint: ["bash", "/usr/local/bin/init-mongo.sh"]

networks:
  mongo_net:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  redis_data: